export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ALL_DETAILS_REQUEST = "ALL_DETAILS_REQUEST";
export const ALL_DETAILS_SUCCESS = "ALL_DETAILS_SUCCESS";
export const ALL_DETAILS_FAIL = "ALL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
